/**
 * FastPack v0 — browser entry point.
 *
 * Imports the self-contained WASM bundle (generated by scripts/embed-wasm.mjs)
 * and exposes `init()` which resolves to the SDK. Fully offline; works from
 * `file://` and `http://`.
 *
 * Usage:
 *   import { init } from "./fastpack-wasm.browser.mjs";
 *   const fp = await init();
 *   const packed = fp.compress(new TextEncoder().encode("hello hello hello"));
 *   const { data } = fp.decompress(packed);
 */

import { createFastPackWasm, embeddedWasmBytes } from "./loader.mjs";
import { B64 } from "./fastpack-wasm.bundle.mjs";

let sdkPromise = null;

/** Initialize (once) and return the FastPack WASM SDK. */
export function init() {
  if (!sdkPromise) {
    sdkPromise = createFastPackWasm(embeddedWasmBytes(B64));
  }
  return sdkPromise;
}

export { FastPackWasmError } from "./loader.mjs";
