/**
 * Build the FastPack WASM single-file bundle for the browser.
 *
 * Steps:
 *   1. `cargo build --release --target wasm32-unknown-unknown` in rs/wasm
 *      (run first; this script uses the existing artifact).
 *   2. Embed the .wasm bytes as base64 into `ts/wasm/fastpack-wasm.bundle.mjs`
 *      as a self-contained module that auto-initializes on first use.
 *
 * Output: a single ESM file with no imports; works from file:// and http://,
 * fully offline. Used by the docs portal and the browser examples.
 */

import { readFileSync, writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const wasmPath = resolve(
  here,
  "../../rs/wasm/target/wasm32-unknown-unknown/release/fastpack_wasm.wasm",
);
const outPath = resolve(here, "../wasm/fastpack-wasm.bundle.mjs");

if (!existsSync(wasmPath)) {
  console.error(
    `wasm artifact not found at ${wasmPath}\n` +
      "Run: cd rs/wasm && cargo build --release --target wasm32-unknown-unknown",
  );
  process.exit(1);
}

const wasmBytes = readFileSync(wasmPath);
const b64 = wasmBytes.toString("base64");

const bundle = `/**
 * FastPack v0 — self-contained WASM bundle (generated by scripts/embed-wasm.mjs).
 * Do not edit by hand. The Rust core is compiled to wasm32-unknown-unknown.
 */
const B64 = ${JSON.stringify(b64)};
export { B64 };
`;

writeFileSync(outPath, bundle);
console.log(`wrote ${outPath} (${wasmBytes.length} wasm bytes, ${b64.length} b64 chars)`);

function existsSync(p) {
  try {
    readFileSync(p);
    return true;
  } catch {
    return false;
  }
}
